//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetOut.Models.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GetOut.Models.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e_____#____________
        ///______#____________
        ///______#_____f__ f__
        ///______#____________
        ///______#            
        ///      #            
        ///      #    #       
        ///###ff##    ########
        ///h     f            
        ///      f           
        ///      f   f h      
        ///      f            
        ///###f ## h          
        ///      #            
        ///   h  #            
        ///   w  #            
        ///      #            
        ///      #            
        ///      # h  P       
        ///      #            .
        /// </summary>
        internal static string Level1 {
            get {
                return ResourceManager.GetString("Level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _________________________#_____________#
        ///__h__e___________________#_____________#
        ///__w______________________#_____________#
        ///_______________________________________#
        ///_______________________________________#
        ///_______________________________________#
        ///_________________________#_____________#
        ///_________________________#_____________#
        ///_________________________#_____________#
        ///_________________________#_____________#
        ///####ff##################################
        ///_____________________f____________#____#
        ///________ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level2 {
            get {
                return ResourceManager.GetString("Level2", resourceCulture);
            }
        }
    }
}
